### ISSUE TITLE
Javascript Track Courses to be Completed

### ISSUE THREAD

**Issue by Hosamov** [Hosamov/Treehouse#2]
## TODO
*Courses left to complete in the Treehouse Javacript Track*

* [ ] Javascript Basics
* [ ] Javascript Numbers
* [ ] Javascript Functions
* [ ] Javascript Loops
* [ ] Javascript Arrays
* [ ] Javascript Objects
* [ ] The Landscape of Javascript
* [ ] Javascript and the DOM
* [ ] AJAX Basics
* [ ] Asynchronous Programming with Javascript
* [ ] Working with the Fetch API
* [ ] Object-Oriented Javascript
* [ ] Object-Oriented Javascript: Challenge
* [ ] Node.js Basics
* [ ] Exploring Javascript Conditionals 
* [ ] Build a Simple Dynamic Site with Node.js
* [ ] npm Basics
* [ ] Using npm as  a Task Runner
* [ ] Express Basics
* [ ] Understanding Closures in Javascript
* [ ] Debug Node Applications with Visual Studio
* [ ] Asynchronous Code in Express
* [ ] REST APIs with Express
* [ ] SQL Basics
* [ ] Modifying Data with SQL
* [ ] Using SQL ORMS with Node.js
* [ ] Using Sequelize ORM With Express

:tada: :tada: :tada:

@Hosamov
